=== juanitonew/juanitonew.github.io/xml/carta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="menu" type="tipomenu" />


  <xs:complexType name="tipomenu">
  <xs:sequence>
  <xs:element name="plato" type="tipoplato" minOccurs="1" maxOccurs="unbounded"/>
  
  </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="tipoplato">
        <xs:sequence>
           <xs:element name="tipo" type="xs:string"/>
           <xs:element name="nombre" type="xs:string"/>
            <xs:element name="precio" type="xs:string" />
            <xs:element name="foto" type="tipourl" />
          
       </xs:sequence>
      </xs:complexType>
      
      <xs:complexType name="tipourl">
        
          <xs:attribute name="src" type="xs:string"/>
       
      </xs:complexType>

      
</xs:schema>

=== juanitonew/juanitonew.github.io/xml/carta.xml
<?xml version="1.0" encoding="UTF-8"?> 
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="carta.xsd">
    <plato>
      <tipo>para_llevar</tipo>
      <nombre>Pollo asado</nombre>
      <precio>8,00 € </precio>
      <foto src="../imagenes/polloasado.jpg"></foto>
   </plato>
	<plato>
      <tipo>para_llevar</tipo>
      <nombre>Medio pollo asado</nombre>
      <precio>4,50 €</precio>
      <foto src="../imagenes/mediopollo.jpg"></foto>
    </plato>
	
	<plato>
      <tipo>para_llevar</tipo>
      <nombre>Ensalada mixta</nombre>
      <precio>10,00 €</precio>
      <foto src="../imagenes/ensaladamixta.jpg"></foto>
    </plato>
    <plato>
      <tipo>para_llevar</tipo>
      <nombre>Alitas de pollo</nombre>
      <precio>8,50 € </precio>
      <foto src="../imagenes/alitas.jpg"></foto>
  </plato>
	<plato>
	    <tipo>para_llevar</tipo>
      <nombre>Tortilla de patatas</nombre>
      <precio>9,00 €</precio>
      <foto src="../imagenes/tortilla.jpg"></foto>
    </plato>
	<plato>
	    <tipo>para_llevar</tipo>
      <nombre>Croquetas</nombre>
      <precio>9,50 €</precio>
      <foto src="../imagenes/croquetas.jpg"></foto>
    </plato>
	<plato>
	    <tipo>para_llevar</tipo>
      <nombre>Mini Empanadillas</nombre>
      <precio>7,00 €</precio>
      <foto src="../imagenes/miniempanadillas.jpg"></foto>
    </plato>
	<plato>
	    <tipo>para_llevar</tipo>
      <nombre>Ensaladilla rusa</nombre>
      <precio>9,00 €</precio>
      <foto src="../imagenes/ensaladilla.jpg"></foto>
    </plato>
	<plato>
	    <tipo>para_llevar</tipo>
      <nombre>Patatas fritas</nombre>
      <precio>4,50 €</precio>
      <foto src="../imagenes/patatas.jpg"></foto>
    </plato>
	<plato>
	    <tipo>para_llevar</tipo>
      <nombre>Pimientos fritos</nombre>
      <precio>5,00 €</precio>
      <foto src="../imagenes/pimientos.jpg"></foto>
    </plato>
	<plato>
	    <tipo>para_llevar</tipo>
      <nombre>Huevos rellenos</nombre>
      <precio>7,00 €</precio>
      <foto src="../imagenes/huevosrellenos.jpg"></foto>
	</plato>	
	<plato>
	    <tipo>para_llevar</tipo>
      <nombre>Magro con tomate</nombre>
      <precio>9,00 €</precio>
      <foto src="../imagenes/magro.jpg"></foto>
    </plato>
	<plato>
	    <tipo>para_llevar</tipo>
      <nombre>Albondigas</nombre>
      <precio>9,50 €</precio>
      <foto src="../imagenes/albondigas.jpg"></foto>
    </plato>
    
   
    <plato>
      <tipo>para_servir</tipo>
      <nombre>Paella Mixta, Marisco, de Pollo o Vegetal</nombre>
      <precio>10,00 €</precio>
      <foto src="../imagenes/paella.jpg"></foto>
    </plato>
  
	
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Chorizo a la sidra</nombre>
      <precio>9,00 €</precio>
      <foto src="../imagenes/chorizo.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Patatas bravas con alioli</nombre>
      <precio>7,00 €</precio>
      <foto src="../imagenes/bravas.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Fuente de patatas</nombre>
      <precio>8,50 €</precio>
      <foto src="../imagenes/fuentepatatas.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Revuelto de ajetes con Huevo y Jamón</nombre>
      <precio>10,00 €</precio>
      <foto src="../imagenes/ajetes.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Revuelto de setas con gambas</nombre>
      <precio>11,00 €</precio>
      <foto src="../imagenes/setas.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Huevos rotos con jamon</nombre>
      <precio>14,00 €</precio>
      <foto src="../imagenes/huevosrotos.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Huevos rotos con jamon y queso de cabra</nombre>
      <precio>15,50 €</precio>
      <foto src="../imagenes/huevosrotos.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Huevos rotos con setas y foie</nombre>
      <precio>16,50 €</precio>
      <foto src="../imagenes/huevosrotos.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Gambas al ajillo</nombre>
      <precio>9,00 €</precio>
      <foto src="../imagenes/gambasajillo.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Calamares</nombre>
      <precio>12,00 €</precio>
      <foto src="../imagenes/calamares.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Lacón a la gallega</nombre>
      <precio>12,00 €</precio>
      <foto src="../imagenes/lacon.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Alitas de pollo</nombre>
      <precio>8,50 €</precio>
      <foto src="../imagenes/alitas.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Croquetas</nombre>
      <precio>9,50 €</precio>
      <foto src="../imagenes/croquetas.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Mini empanadillas</nombre>
      <precio>7,00 €</precio>
      <foto src="../imagenes/miniempanadillas.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Nuggets de pollo</nombre>
      <precio>9,00 €</precio>
      <foto src="../imagenes/nuggets.jpg"></foto>
    </plato>
	
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Costillar de cerdo con salsa barbacoa</nombre>
      <precio>19,00 €</precio>
      <foto src="../imagenes/costillar.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Churrasco a la plancha</nombre>
      <precio>19,00 €</precio>
      <foto src="../imagenes/churrasco.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Solomillitos de cerdo con salsa chimichurri</nombre>
      <precio>17,00 €</precio>
      <foto src="../imagenes/solomillos.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Salchichas Frankfurt(3)</nombre>
      <precio>12,00 €</precio>
      <foto src="../imagenes/salchi.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Salchicas Frankfurt (6)</nombre>
      <precio>18,00 €</precio>
      <foto src="../imagenes/salchi2.jpg"></foto>
    </plato>
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Combo Criscel</nombre>
      <precio>35,00 €</precio>
      <foto src="../imagenes/combo.jpg"></foto>
    </plato>
	


	<plato>
	<tipo>para_servir</tipo>
      <nombre>Numero 1:2 huevos fritos,2 salchichas,2cintas de lomo y patatas fritas</nombre>
      <precio>7,50 €</precio>
      <foto src="../imagenes/comb1.jpg"></foto>
    </plato>
    <plato>
    <tipo>para_servir</tipo>
      <nombre>Numero 2: Escalope de ternera con ensalada.</nombre>
      <precio>8,50 €</precio>
      <foto src="../imagenes/escalope.jpg"></foto>
    </plato>
    <plato>
    <tipo>para_servir</tipo>
      <nombre>Numero 3: 1 Huevo frito 4 tidas de bacon 1 filete de hamburguesa y patatas fritas</nombre>
      <precio>7,50 €</precio>
      <foto src="../imagenes/comb2.jpg"></foto>
    </plato>
    <plato>
    <tipo>para_servir</tipo>
      <nombre>Numero 4:Tortilla francesa 2 cintas de lomo 2 salchichas y patatas fritas</nombre>
      <precio>7,50 €</precio>
      <foto src="../imagenes/comb3.jpg"></foto>
    </plato>
		
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Ensalada mixta</nombre>
      <precio>10,00 €</precio>
      <foto src="../imagenes/emixta.jpg"></foto>
    </plato>
<plato>
<tipo>para_servir</tipo>
      <nombre>Ensalada cesar</nombre>
      <precio>11,50 €</precio>
      <foto src="../imagenes/ecesar.jpg"></foto>
    </plato>
<plato>
<tipo>para_servir</tipo>
      <nombre>Ensalada caprese</nombre>
      <precio>10,00 €</precio>
      <foto src="../imagenes/ecaprese.jpg"></foto>
    </plato>
<plato>
<tipo>para_servir</tipo>
      <nombre>Ensalada de salmon</nombre>
      <precio>14,00 €</precio>
      <foto src="../imagenes/esalmon.jpg"></foto>
    </plato>
<plato>
<tipo>para_servir</tipo>
      <nombre>Ensalada de Bacon, pollo y queso de cabra</nombre>
      <precio>12,00 €</precio>
      <foto src="../imagenes/ebacon.jpg"></foto>
    </plato>

	
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Hamburguesa normal</nombre>
      <precio>7,50 €</precio>
      <foto src="../imagenes/hamburguesas.jpg"></foto>
    </plato>
    <plato>
    <tipo>para_servir</tipo>
      <nombre>Hamburguesa normal con huevo</nombre>
      <precio>8,20 €</precio>
      <foto src="../imagenes/hconhuevo.jpg"></foto>
    </plato>
    <plato>
    <tipo>para_servir</tipo>
      <nombre>Hamburguesa especial</nombre>
      <precio>8,50 €</precio>
      <foto src="../imagenes/hamburguesa.jpg"></foto>
    </plato>
    <plato>
    <tipo>para_servir</tipo>
      <nombre>Hamburguesa especial con huevo frito</nombre>
      <precio>9,20 €</precio>
      <foto src="../imagenes/hamburguesa.jpg"></foto>
    </plato>
    <plato>
    <tipo>para_servir</tipo>
      <nombre>Hamburguesa de pollo</nombre>
      <precio>6,50 €</precio>
      <foto src="../imagenes/hpollo.jpg"></foto>
    </plato>
    <plato>
    <tipo>para_servir</tipo>
      <nombre>Hamburguesa Criscel</nombre>
      <precio>13,00 €</precio>
      <foto src="../imagenes/hamburguesa.jpg"></foto>
    </plato>
	
	<plato>
	<tipo>para_servir</tipo>
      <nombre>Sandwich mixto</nombre>
      <precio>3,50 €</precio>
      <foto src="../imagenes/mixto.jpg"></foto>
    </plato>
   <plato>
   <tipo>para_servir</tipo>
      <nombre>Sandwich mixto con huevo frito</nombre>
      <precio>4,20 €</precio>
      <foto src="../imagenes/smconhuevo.jpg"></foto>
    </plato>
   <plato>
   <tipo>para_servir</tipo>
      <nombre>Sandwich vegetal</nombre>
      <precio>5,50 €</precio>
      <foto src="../imagenes/svegetal.jpg"></foto>
    </plato>
   <plato>
   <tipo>para_servir</tipo>
      <nombre>Sandwich vegetal con atun</nombre>
      <precio>6,20 €</precio>
      <foto src="../imagenes/vegeatun.jpg"></foto>
    </plato>
   <plato>
   <tipo>para_servir</tipo>
      <nombre>Sandwich Criscel</nombre>
