=== juanitonew/juanitonew.github.io/xml/eventos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="eventos" type="tipoeventos" />


  <xs:complexType name="tipoeventos">
  <xs:sequence>
  <xs:element name="talleres" type="tipotalleres" minOccurs="1" maxOccurs="unbounded"/>
  
  </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="tipotalleres">
        <xs:sequence>
           <xs:element name="tipo" type="xs:string"/>
           <xs:element name="nombre" type="xs:string"/>
            <xs:element name="fecha" type="xs:date" />
            <xs:element name="precio" type="xs:string" />
          
       </xs:sequence>
      </xs:complexType>
</xs:schema>

=== juanitonew/juanitonew.github.io/xml/eventos.xml
<?xml version="1.0" encoding="UTF-8"?>
<eventos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="eventos.xsd">
    <talleres>
      <tipo>taller</tipo>
      <nombre>taller de cocina</nombre>
      <fecha>2019-06-12</fecha>
      <precio>Gratuito</precio>
    </talleres>
    <talleres>
      <tipo>taller</tipo>
      <nombre>taller de reposteria</nombre>
      <fecha>2019-06-16</fecha>
      <precio>Gratuito</precio>
    </talleres>
    </eventos>
